# Project information
site_name: ETK's Blog
site_url: https://yifank.github.io/
site_author: Yifan Kang
site_description: >-
  Some random blogs on Math, Informatics, Physics Olympiads and more.
theme:
  name: material
  features:
    - header.autohide
  # 一些扩展功能。 
  feature:
    - tabs: true
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  font:
    text: Play
    code: Fira Code
#Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/YIFANK
# 这些是用来渲染数学公式的，需要 polyfill.min.js 和 tex-chtml.min.js # 可以自己丢到博客目录下，也可以直接像我这样引用。
# 下面 md ext 里的 math 没用，渲染效果很拉，所以用 js。 
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/mathjax/3.2.0/es5/tex-chtml.min.js
# markdown 扩展语法 
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - mdx_math