# Project information
site_name: Yifan Kang's Blog
site_url: https://yifank.github.io/
site_author: Yifan Kang
site_description: >-
  Some random blogs on Math, Informatics, Physics Olympiads and more.
theme:
  name: material
  custom_dir: overrides
  # 一些扩展功能。 
  features:
    # - navigation.instant # 点击内部链接时，不用全部刷新页面 # 会导致 数学公式第一次进入时加载失败
    - navigation.tracking # 在url中使用标题定位锚点
    - navigation.tabs # 顶部显示导航顶层nav（也就是第一个节点）
    - navigation.tabs.sticky # 滚动时隐藏顶部nav，需要配合navigation.tabs使用
    - navigation.sections # nav节点缩进
    # - navigation.expand # 不折叠左侧nav节点
    - navigation.indexes # 指定节点index pages ，跟instant不兼容
    - toc.integrate # 右侧生产目录
    - toc.follow
    - navigation.top # 一键回顶部
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.footer
  font:
    text: Play
    code: Fira Code
#Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/YIFANK
# 这些是用来渲染数学公式的，需要 polyfill.min.js 和 tex-chtml.min.js # 可以自己丢到博客目录下，也可以直接像我这样引用。
# 下面 md ext 里的 math 没用，渲染效果很拉，所以用 js。 
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/mathjax/3.2.0/es5/tex-chtml.min.js
# markdown 扩展语法 
plugins:
  - meta
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
      linenums: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - mdx_math
